import * as React from "react";
import { DocsLayout } from "src/pages/docs/DocsLayout";

export class IntroductionDoc extends React.Component<{}, {}> {

  public render() {
    return (
      <DocsLayout>
        <h1>Introduction</h1>

        <section>
          <h2>Features</h2>

          <h4>Admin UI</h4>
          <p>
            Crud wizard uses OpenAPI specifications to render <strong>create</strong>, <strong>read</strong>, <strong>update</strong> and <strong>delete</strong> UI for resources defined by its users. It is similar to <a href="https://swagger.io/tools/swagger-ui/" target="_blank">Swagger UI</a>, but generates a fully functional admin UI instead of indivudual forms for each operation. Think <a href="https://keystonejs.com/" target="_blank">KeystoneJS</a> admin UI, or <a href="https://www.djangoproject.com/" target="_blank">django</a> admin. The admin UI generated by crud wizard consists of the following components:
          </p>
          <ul>
            <li>Navigation panel</li>
            <li>Create window</li>
            <li>List window</li>
            <li>Detail window</li>
            <li>Update window</li>
          </ul>
        </section>

        <section>
          <h2>Use Cases</h2>

          <h4>Internal Admin UI</h4>
          <p>As products begin to expose more of their core services using APIs that can be accessed programatically, the need for customer-facing user interfaces completely disappears in some cases. Popular examples of this type of product include <a href="https://www.twilio.com/" target="_blank">Twilio</a> and <a href="https://stripe.com/" target="_blank">Stripe</a>. When these types of companies are just getting started, they may not have the time or resources to build a polished user interface for their backend API, but still need some way to browse and manage resources using a GUI. Instead of hiring a frontend developer or spending time setting up tools that need to be built and deployed manually, they can use crud wizard to generate an Admin UI that covers 80% of their needs without having to change any of their existing code.</p>

          <h4>Development Tool</h4>
          <p>Crud wizard projects can be used alongside other tools like Postman or Swagger UI to give developers quick access to their API without having to spend time manually crafting calls to backend services. While Swagger UI provides fine-grained access to each operation in the spec, crud wizard's admin UI can provide a high-level, configurable UX that makes managing resources exposed by APIs more convenient.</p>
        </section>

      </DocsLayout>
    )
  }
}